"""added audit columns to checkins

Revision ID: 65272e66daf5
Revises: 
Create Date: 2021-01-30 13:42:25.023535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65272e66daf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('created_datetime', sa.DateTime(), nullable=True))
    op.add_column('checkins', sa.Column('updated_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkins', 'updated_datetime')
    op.drop_column('checkins', 'created_datetime')
    # ### end Alembic commands ###
